// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuTIcEhwjLTVQ7OWnVzn3JYJEK3phpAeM',
    appId: '1:75335575020:web:4fb785edd06e074e24ccc9',
    messagingSenderId: '75335575020',
    projectId: 'saudeemcasa-demo',
    authDomain: 'saudeemcasa-demo.firebaseapp.com',
    storageBucket: 'saudeemcasa-demo.firebasestorage.app',
    measurementId: 'G-18MZKSGJC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7FhbQEytKsqCKEj36NtEU4WZ33N4cZ7M',
    appId: '1:75335575020:android:205f3d1d91cc249924ccc9',
    messagingSenderId: '75335575020',
    projectId: 'saudeemcasa-demo',
    storageBucket: 'saudeemcasa-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7pb0UP28-vvOM810Eu-RD8kmV7d7GSR4',
    appId: '1:75335575020:ios:dae4b6e0484ae8a124ccc9',
    messagingSenderId: '75335575020',
    projectId: 'saudeemcasa-demo',
    storageBucket: 'saudeemcasa-demo.firebasestorage.app',
    iosBundleId: 'com.portifolio.linozeferino.saudeemcasa',
  );
}
